name       : messagelib
version    : 21.04.1
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/messagelib-21.04.1.tar.xz : 9b6a97cc1348591d0dbdf7b01f3a6216aaa86ca5c9667f8ae2b1dc398178c7ec
homepage   : https://kde.org/
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM messaging library
description: |
    KDE PIM messaging library.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(qca2-qt5)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - karchive-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - knewstuff-devel
    - libgravatar-devel
    - libkdepim-devel
    - libkleo-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
