name       : messagelib
version    : 22.04.3
release    : 70
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/messagelib-22.04.3.tar.xz : 50de2bdd2bdba547b8b318a0ad075a1176f496457056988a2709ea94915a7a1b
homepage   : https://kde.org/
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM messaging library
description: |
    KDE PIM messaging library.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(qca2-qt5)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - karchive-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - knewstuff-devel
    - knotifications-devel
    - libgravatar-devel
    - libkdepim-devel
    - libkleo-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
