name       : messagelib
version    : 20.12.3
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/messagelib-20.12.3.tar.xz : 3aae37239d281aa6137b57baa5ac8834f5f95786847cc72fd879f664fce12c23
homepage   : https://kde.org/
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM messaging library
description: |
    KDE PIM messaging library.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(qca2-qt5)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - karchive-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - knewstuff-devel
    - libgravatar-devel
    - libkdepim-devel
    - libkleo-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
