name       : messagelib
version    : 18.12.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/messagelib-18.12.0.tar.xz : dbce3465e52030d632142fb7de112eb00f3fe44d695ea142de0463baa8b12ba1
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM messaging library
description: |
    KDE PIM messaging library.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - kcalcore-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - kdepim-apps-libs-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - kmime-devel
    - kpimtextedit-devel
    - kwallet-devel
    - libassuan-devel
    - libboost-devel
    - libgravatar-devel
    - libical-devel
    - libkdepim-devel
    - libkleo-devel
    - openldap-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
