name       : messagelib
version    : 17.08.2
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/messagelib-17.08.2.tar.xz : 750a6ff5e641d2fe2ef12e6186da412b0884e32fd99c5921df9cbeb358386371
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : KDE PIM messaging library.
description: |
    KDE PIM messaging library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - kcalcore-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - kdepim-apps-libs-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - kmime-devel
    - kpimtextedit-devel
    - kwallet-devel
    - libassuan-devel
    - libboost-devel
    - libgravatar-devel
    - libical-devel
    - libkdepim-devel
    - libkleo-devel
    - openldap-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
