name       : messagelib
version    : 19.08.3
release    : 32
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/messagelib-19.08.3.tar.xz : db2e48e48d87922f9533ebd3eb021549e6bf8dea5828d83bfdfecb36b1426728
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM messaging library
description: |
    KDE PIM messaging library.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - karchive-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libgravatar-devel
    - libical-devel
    - libkdepim-devel
    - libkleo-devel
    - openldap-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
