name       : messagelib
version    : 20.12.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/messagelib-20.12.0.tar.xz : b0a126d2544b3cdfb025caca6374dad2708e9112fe4118f8a94684a9c15fc3f1
homepage   : https://kde.org/
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM messaging library
description: |
    KDE PIM messaging library.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(libsasl2)
    - pkgconfig(qca2-qt5)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - karchive-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libgravatar-devel
    - libical-devel
    - libkdepim-devel
    - libkleo-devel
    - openldap-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
