name       : messagelib
version    : 23.04.2
release    : 75
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/messagelib-23.04.2.tar.xz : 9b9fcce6bec1c4b499b30b32ff37c76953a8bff46c2e39eb67844f96ef14d88e
homepage   : https://kde.org/
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM messaging library
description: |
    KDE PIM messaging library.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(qca2-qt5)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - karchive-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - knewstuff-devel
    - knotifications-devel
    - ktextaddons-devel
    - libgravatar-devel
    - libkdepim-devel
    - libkleo-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
