name       : messagelib
version    : 20.08.2
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/messagelib-20.08.2.tar.xz : 5cf3a3f2b6473e60a7c2af10aa4eb1cfba25a4786132ee87b657b0dafb9f5028
homepage   : https://kde.org/
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM messaging library
description: |
    KDE PIM messaging library.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - karchive-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kldap-devel
    - kmailtransport-devel
    - kmbox-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libgravatar-devel
    - libical-devel
    - libkdepim-devel
    - libkleo-devel
    - openldap-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
